name: Gradle publish jar
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Debug GitHub Secrets
        run: |
          echo "Checking if secrets are loaded..."
          echo "SIGNING_KEY length: ${#SIGNING_KEY}"
          echo "SIGNING_PASSWORD length: ${#SIGNING_PASSWORD}"
        env:
          SIGNING_KEY: ${{ secrets.PGP_KEY }}
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}
      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.PGP_PASSPHRASE }}
        run: ./gradlew publish --info --stacktrace